# Generated by Django 3.1.4 on 2020-12-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('singer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('song_name', models.CharField(max_length=200)),
                ('song_publish_date', models.DateField()),
            ],
        ),
    ]
