# Generated by Django 3.1.4 on 2020-12-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20201220_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
